import type { Cart } from '../types';
import { ApiError, serverApi, type SaleCommitInput, type ServerSaleCommit } from './serverApi';

const DB_NAME='zhirox-offline-v19'; const DB_VERSION=1; const LEASE_KEY='active-lease';
export interface OfflineLeaseGrant{lease_id:string;device_id:string;starts_at:string;expires_at:string;lease_token:string;block:{id:string;business_date:string;receipt_prefix:string;start_sequence:number;end_sequence:number};}
export interface StoredOfflineLease extends OfflineLeaseGrant{next_sequence:number;}
export interface OfflineReceiptProof{lease_id:string;lease_token:string;block_id:string;receipt_number:string;business_date:string;sequence:number;captured_at:string;}
export interface QueuedOfflineSale{idempotencyKey:string;operationId:string;payload:SaleCommitInput;provisionalSaleId:string;cartSnapshot:Cart;userId:string;createdAt:string;lastError?:string;}

const openDb=()=>new Promise<IDBDatabase>((resolve,reject)=>{const request=indexedDB.open(DB_NAME,DB_VERSION);request.onupgradeneeded=()=>{const db=request.result;if(!db.objectStoreNames.contains('meta'))db.createObjectStore('meta');if(!db.objectStoreNames.contains('sales'))db.createObjectStore('sales',{keyPath:'idempotencyKey'});};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});
const requestValue=<T>(request:IDBRequest<T>)=>new Promise<T>((resolve,reject)=>{request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});
const txDone=(tx:IDBTransaction)=>new Promise<void>((resolve,reject)=>{tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error||new Error('IDB_ABORT'));});
export const businessDateBaghdad=()=>{const parts=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Baghdad',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date());const map=Object.fromEntries(parts.map(p=>[p.type,p.value]));return `${map.year}-${map.month}-${map.day}`;};

export async function saveOfflineLease(grant:OfflineLeaseGrant){const db=await openDb();const tx=db.transaction('meta','readwrite');tx.objectStore('meta').put({...grant,next_sequence:grant.block.start_sequence} satisfies StoredOfflineLease,LEASE_KEY);await txDone(tx);db.close();}
export async function getOfflineLease():Promise<StoredOfflineLease|null>{const db=await openDb();const tx=db.transaction('meta','readonly');const value=await requestValue(tx.objectStore('meta').get(LEASE_KEY));await txDone(tx);db.close();return (value as StoredOfflineLease)||null;}
export async function clearOfflineLease(){const db=await openDb();const tx=db.transaction('meta','readwrite');tx.objectStore('meta').delete(LEASE_KEY);await txDone(tx);db.close();}
export async function reserveOfflineReceipt():Promise<OfflineReceiptProof>{const db=await openDb();return new Promise((resolve,reject)=>{const tx=db.transaction('meta','readwrite');const store=tx.objectStore('meta');const get=store.get(LEASE_KEY);let proof:OfflineReceiptProof|undefined;get.onerror=()=>reject(get.error);get.onsuccess=()=>{const lease=get.result as StoredOfflineLease|undefined;if(!lease){tx.abort();reject(new ApiError(0,'OFFLINE_LEASE_REQUIRED'));return;}const now=new Date();if(now>new Date(lease.expires_at)){tx.abort();reject(new ApiError(0,'OFFLINE_LEASE_EXPIRED'));return;}if(lease.block.business_date!==businessDateBaghdad()){tx.abort();reject(new ApiError(0,'OFFLINE_RECEIPT_DATE_CHANGED'));return;}if(lease.next_sequence>lease.block.end_sequence){tx.abort();reject(new ApiError(0,'OFFLINE_RECEIPT_BLOCK_EXHAUSTED'));return;}const sequence=lease.next_sequence;const receipt_number=`${lease.block.receipt_prefix}-${lease.block.business_date.split('-').join('')}-${String(sequence).padStart(6,'0')}`;proof={lease_id:lease.lease_id,lease_token:lease.lease_token,block_id:lease.block.id,receipt_number,business_date:lease.block.business_date,sequence,captured_at:now.toISOString()};store.put({...lease,next_sequence:sequence+1},LEASE_KEY);};tx.oncomplete=()=>{db.close();if(proof)resolve(proof);else reject(new Error('OFFLINE_RECEIPT_NOT_RESERVED'));};tx.onerror=()=>{db.close();reject(tx.error)};tx.onabort=()=>db.close();});}
export async function queueOfflineSale(record:QueuedOfflineSale){const db=await openDb();const tx=db.transaction('sales','readwrite');tx.objectStore('sales').put(record);await txDone(tx);db.close();}
export async function pendingOfflineSales():Promise<QueuedOfflineSale[]>{const db=await openDb();const tx=db.transaction('sales','readonly');const rows=await requestValue(tx.objectStore('sales').getAll()) as QueuedOfflineSale[];await txDone(tx);db.close();return rows.sort((a,b)=>a.createdAt.localeCompare(b.createdAt));}
export async function pendingOfflineCount(){return (await pendingOfflineSales()).length;}
async function deleteQueued(key:string){const db=await openDb();const tx=db.transaction('sales','readwrite');tx.objectStore('sales').delete(key);await txDone(tx);db.close();}
async function markQueuedError(record:QueuedOfflineSale,error:string){await queueOfflineSale({...record,lastError:error});}

export async function flushOfflineQueue(){const rows=await pendingOfflineSales();let synced=0;for(const record of rows){try{const response=await serverApi.commitSale(record.payload,record.idempotencyKey);const {useDataStore}=await import('../stores/dataStore');useDataStore.getState().reconcileOfflineSale(record.provisionalSaleId,response,record.userId,record.cartSnapshot);await deleteQueued(record.idempotencyKey);synced+=1;}catch(error){const code=error instanceof ApiError?error.code:'UNKNOWN_ERROR';await markQueuedError(record,code);if(code==='NETWORK_UNAVAILABLE'||code==='AUTH_REQUIRED'||(error instanceof ApiError&&error.status===401))break;}}
return {synced,pending:(await pendingOfflineSales()).length};}

export function provisionalResponseFromCart(cart:Cart,receipt:OfflineReceiptProof,operationId:string):ServerSaleCommit{
  const debt=cart.debt_amount;const currentBalance=cart.customer_id?null:null;
  return {sale_id:`offline-${operationId}`,receipt_number:receipt.receipt_number,payment_method:cart.payment_type,paid_method:cart.paid_amount>0?'cash':null,customer_id:cart.customer_id||null,subtotal_iqd:cart.subtotal,discount_iqd:cart.discount_amount,total_iqd:cart.total_amount,paid_iqd:cart.paid_amount,debt_iqd:debt,customer_balance_iqd:currentBalance,items:cart.items.map(item=>({product_id:item.product.id,product_name:item.product.name,barcode:item.product.barcode,quantity:item.quantity,unit_price_iqd:item.unit_price,unit_cost_iqd:item.product.cost_price,line_total_iqd:item.total_price,stock_after:item.product.stock_quantity-item.quantity}))};
}
