import assert from 'node:assert/strict';import fs from 'node:fs/promises';import http from 'node:http';import pg from 'pg';import {createHandler} from '../src/app.mjs';
const {Pool}=pg;if(!process.env.DATABASE_URL)throw new Error('DATABASE_URL required');const pool=new Pool({connectionString:process.env.DATABASE_URL,max:30});const migrations=['001_core.sql','002_financial.sql','003_catalog.sql','004_daily_authority.sql','005_offline_leases.sql','006_user_management.sql','007_backup_ops.sql','008_catalog_performance.sql'];for(const file of migrations)await pool.query(await fs.readFile(new URL(`../db/${file}`,import.meta.url),'utf8'));await pool.query('TRUNCATE backup_runs,security_audit,receipt_blocks,offline_leases,devices,journal_lines,journal_batches,stock_movements,payments,sale_items,sales,customer_balances,customers,products,categories,idempotency_keys,receipt_sequences,auth_throttle,sessions,users,branches,markets CASCADE');
let cookie='';const deviceId='load-device-main-0001';const handler=createHandler(pool,{production:false,bootstrapToken:'load-bootstrap-token',offlineLeaseSecret:'load-offline-secret-which-is-long-enough',timeZone:'Asia/Baghdad'});const server=http.createServer(handler);await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const base=`http://127.0.0.1:${server.address().port}`;
async function request(path,{method='GET',body,headers={}}={}){const response=await fetch(base+path,{method,headers:{origin:'http://127.0.0.1','x-device-id':deviceId,...(cookie?{cookie}:{}),...(body?{'content-type':'application/json'}:{}),...headers},body:body?JSON.stringify(body):undefined});const setCookie=response.headers.get('set-cookie');if(setCookie)cookie=setCookie.split(';')[0];let json={};try{json=await response.json();}catch{}return{response,json};}
const started=performance.now();let r=await request('/api/v1/bootstrap',{method:'POST',headers:{'x-bootstrap-token':'load-bootstrap-token'},body:{marketName:'20K Load Market',fullName:'Load Owner',username:'loadowner',password:'LoadPassword20',receiptPrefix:'LOAD'}});assert.equal(r.response.status,201);r=await request('/api/v1/devices/register',{method:'POST',body:{device_id:deviceId,label:'20K Load POS'}});assert.equal(r.response.status,200);
const products=Array.from({length:20000},(_,i)=>{const n=i+1;return{id:`load-product-${String(n).padStart(5,'0')}`,barcode:`LOAD-${String(n).padStart(8,'0')}`,barcodes:[`ALT-${String(n).padStart(8,'0')}`],name:`کالای تاقیکردنەوە ${n}`,cost_price_iqd:500+(n%50),sale_price_iqd:1000+(n%100),stock_quantity:100,low_stock_limit:5,currency:'IQD'};});
const importStart=performance.now();for(let offset=0;offset<products.length;offset+=500){const batch=products.slice(offset,offset+500);const imported=await request('/api/v1/catalog/products/import',{method:'POST',headers:{'idempotency-key':`load-import-${offset/500}`},body:{items:batch}});assert.equal(imported.response.status,201,`import batch ${offset}: ${JSON.stringify(imported.json)}`);assert.equal(imported.json.imported,batch.length);}const importMs=performance.now()-importStart;const count=await pool.query('SELECT count(*)::int AS count FROM products');assert.equal(count.rows[0].count,20000);
const listStart=performance.now();let after='';let listed=0;do{const query=new URLSearchParams({limit:'500'});if(after)query.set('after_id',after);const page=await request(`/api/v1/catalog/products?${query}`);assert.equal(page.response.status,200);listed+=page.json.items.length;after=page.json.next_after_id||'';}while(after);const listMs=performance.now()-listStart;assert.equal(listed,20000);
const lookupStart=performance.now();for(let i=1;i<=500;i++){const n=((i*37)%20000)+1;const barcode=i%2===0?`ALT-${String(n).padStart(8,'0')}`:`LOAD-${String(n).padStart(8,'0')}`;const found=await request(`/api/v1/catalog/products/lookup?barcode=${encodeURIComponent(barcode)}`);assert.equal(found.response.status,200);assert.equal(found.json.product.id,`load-product-${String(n).padStart(5,'0')}`);}const lookupMs=performance.now()-lookupStart;
const saleStart=performance.now();const sales=Array.from({length:100},(_,i)=>{const n=i+1;const price=1000+(n%100);return request('/api/v1/sales/commit',{method:'POST',headers:{'idempotency-key':`load-sale-key-${i}`},body:{client_operation_id:`load-sale-operation-${i}`,payment_method:'cash',paid_iqd:price,items:[{product_id:`load-product-${String(n).padStart(5,'0')}`,quantity:1}]}});});const results=await Promise.all(sales);assert.ok(results.every(x=>x.response.status===201),results.filter(x=>x.response.status!==201).slice(0,3).map(x=>x.json));assert.equal(new Set(results.map(x=>x.json.receipt_number)).size,100);const saleMs=performance.now()-saleStart;const stock=await pool.query("SELECT count(*)::int AS count FROM products WHERE id LIKE 'load-product-%' AND stock_quantity=99");assert.equal(stock.rows[0].count,100);
const totalMs=performance.now()-started;const metrics={products:20000,import_ms:Math.round(importMs),list_ms:Math.round(listMs),lookup_500_ms:Math.round(lookupMs),concurrent_sales_100_ms:Math.round(saleMs),total_ms:Math.round(totalMs)};console.log(JSON.stringify(metrics));assert.ok(importMs<180000,`20k import too slow: ${importMs}ms`);assert.ok(listMs<30000,`20k listing too slow: ${listMs}ms`);assert.ok(lookupMs<30000,`500 lookups too slow: ${lookupMs}ms`);assert.ok(saleMs<30000,`100 concurrent sales too slow: ${saleMs}ms`);await new Promise(resolve=>server.close(resolve));await pool.end();
